### ISSUE TITLE
Compatibility issue with Magento SUPEE-6788?

### ISSUE THREAD

**Issue by grafikchaos** [fsecommerce/convertizer_magento#1]
With Magento Patch [SUPEE-6788](https://magento.com/security/patches/supee-6788), should you be utilizing the `<use>admin</use>` in your admin routes?

https://github.com/fsecommerce/convertizer_magento/blob/master/app/code/local/Fsecommerce/Convertizer/etc/config.xml#L51-L64

```
<admin>
    <routers>
        <fsecommerce_convertizer>
        	<use>admin</use>
            <args>
            	<frontName>convertizer</frontName>
				<module>Fsecommerce_Convertizer</module>
                <modules>
                    <Fsecommerce_Convertizer before="Mage_Adminhtml">Fsecommerce_Convertizer_Adminhtml</Fsecommerce_Convertizer>
                </modules>
            </args>
        </fsecommerce_convertizer>
    </routers>
</admin>
```

should be:

```
<admin>
    <routers>
        <adminhtml>
            <args>
                <modules>
                    <Fsecommerce_Convertizer_Adminhtml before="Mage_Adminhtml">Fsecommerce_Convertizer_Adminhtml</Fsecommerce_Convertizer_Adminhtml>
                </modules>
            </args>
        </adminhtml>
    </routers>
</admin>
```

And then fix the `Fsecommerce_Convertizer_Block_Adminhtml_Feed ::generateFeed()` and `Fsecommerce_Convertizer_Block_Adminhtml_Feed::()getFeedData` methods to use the correct URL

https://github.com/fsecommerce/convertizer_magento/blob/master/app/code/local/Fsecommerce/Convertizer/Block/Adminhtml/Feed.php#L30-L37
``` 
/**
 * Return ajax url for button
 *
 * @return string
 */
public function generateFeed()
{	
	return Mage::helper('adminhtml')->getUrl('convertizer/adminhtml_feed/generate');
}

public function getFeedData(){
	return Mage::helper('adminhtml')->getUrl('convertizer/adminhtml_feed/generate');
}
```	

You can use this tool to help fix the issue:

https://github.com/rhoerr/supee-6788-toolbox#technical-details

**Comment by fsecommerce** [comment]
@grafikchaos many thanks for this advice. We have fixed this issue just now.
https://github.com/fsecommerce/convertizer_magento/commit/565a0bf54311233ad464daf757167027ee2265c5
